<ul class="page-breadcrumb">
    <?php
    /**
     * @var $page Zend\Navigation\Page\Mvc
     */
    foreach ($this->pages as $page) {
        $a_class = $page->getClass();
        $a_class .= ($page->getActive() == 1) ? ' active' : '';
        ?>
        <li>
            <a href="<?= $page->getHref() ?>" class="<?= $a_class; ?>"><?= $page->getLabel(); ?></a>
            <?php if ($page->getActive() != 1) { ?>
                <i class="fa fa-circle"></i>
            <?php } ?>
        </li>
        <?php
    }
    ?>
</ul>
