<?php
?>
<?php echo $this->doctype() ?>
<!--[if IE 8]>
<html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <!--    --><?php //echo $this->headTitle('General Cavi Applicazione')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico']); ?>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->

    <?php $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all')
        ->appendStylesheet($this->url('assets') . 'metronic/theme/assets/global/plugins/font-awesome/css/font-awesome.min.css')
        ->appendStylesheet($this->url('assets') . 'metronic/theme/assets/global/plugins/simple-line-icons/simple-line-icons.min.css')
        ->appendStylesheet($this->url('assets') . 'metronic/theme/assets/global/plugins/bootstrap/css/bootstrap.min.css')
        ->appendStylesheet($this->url('assets') . 'metronic/theme/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css'); ?>
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <?php $this->headLink()
        ->appendStylesheet($this->url('assets') . 'metronic/theme/assets/global/plugins/select2/css/select2.min.css')
        ->appendStylesheet($this->url('assets') . 'metronic/theme/assets/global/plugins/select2/css/select2-bootstrap.min.css');
    ?>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN THEME GLOBAL STYLES -->
    <?php $this->headLink()
        ->appendStylesheet($this->url('assets') . 'metronic/theme/assets/global/css/components.min.css', 'all', true, array('id' => 'style_components'))
        ->appendStylesheet($this->url('assets') . 'metronic/theme/assets/global/css/plugins.min.css');
    ?>
    <!-- END THEME GLOBAL STYLES -->
    <!-- BEGIN PAGE LEVEL STYLES -->
    <?php $this->headLink()
        ->appendStylesheet($this->url('assets') . 'metronic/theme/assets/pages/css/login.min.css');
    ?>
    <!-- END PAGE LEVEL STYLES -->
    <!-- BEGIN THEME LAYOUT STYLES -->
    <!-- END THEME LAYOUT STYLES -->
    <?php echo $this->headLink(); ?>


    <!-- Scripts -->
    <?php $this->headScript()
        ->appendFile($this->url('assets') . 'metronic/theme/assets/global/plugins/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
        ->appendFile($this->url('assets') . 'metronic/theme/assets/global/plugins/excanvas.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
        ->appendFile($this->url('assets') . 'metronic/theme/assets/global/plugins/ie8.fix.min.js', 'text/javascript', array('conditional' => 'lt IE 9'));
    ?>
    <!-- BEGIN CORE PLUGINS -->
    <?php $this->headScript()
        ->appendFile($this->url('assets') . 'metronic/theme/assets/global/plugins/jquery.min.js', 'text/javascript')
        ->appendFile($this->url('assets') . 'metronic/theme/assets/global/plugins/bootstrap/js/bootstrap.min.js', 'text/javascript')
        ->appendFile($this->url('assets') . 'metronic/theme/assets/global/plugins/js.cookie.min.js', 'text/javascript')
        ->appendFile($this->url('assets') . 'metronic/theme/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js', 'text/javascript')
        ->appendFile($this->url('assets') . 'metronic/theme/assets/global/plugins/jquery.blockui.min.js', 'text/javascript')
        ->appendFile($this->url('assets') . 'metronic/theme/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js', 'text/javascript');
    ?>
    <!-- END CORE PLUGINS -->
    <!-- BEGIN GLOBAL PLUGINS -->
    <?php $this->headScript()
        ->appendFile($this->url('assets') . 'metronic/theme/assets/global/scripts/app.min.js', 'text/javascript');
    ?>
    <!-- END GLOBAL PLUGINS -->
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <?php $this->headScript()
        ->appendFile($this->url('assets') . 'metronic/theme/assets/global/plugins/jquery-validation/js/jquery.validate.min.js', 'text/javascript')
        ->appendFile($this->url('assets') . 'metronic/theme/assets/global/plugins/jquery-validation/js/additional-methods.min.js', 'text/javascript')
        ->appendFile($this->url('assets') . 'metronic/theme/assets/global/plugins/select2/js/select2.full.min.js', 'text/javascript');
    ?>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN THEME GLOBAL SCRIPTS -->
    <!-- END THEME GLOBAL SCRIPTS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <?php $this->headScript()
        ->appendFile($this->url('assets') . 'metronic/theme/assets/pages/scripts/login.min.js', 'text/javascript');
    ?>
    <!-- END PAGE LEVEL SCRIPTS -->


    <?php echo $this->headScript(); ?>
</head>

<body class="login">
<!-- BEGIN LOGO -->
<div class="logo">
    <a href="<?= $this->url('home'); ?>">
        <div style="font-size: 1.2em;font-weight: bold; color: white; margin-top: 1em">GENERAL<span style="color: blue">CAVI</span>
        </div>
    </a>
</div>
</div>
<!-- END LOGO -->
<!-- BEGIN CONTENT BODY -->
<div class="content">
    <?php echo $this->content ?>
</div>
<!-- END CONTENT BODY -->
<!-- END CONTENT -->
<!-- END FOOTER -->
<?php echo $this->inlineScript() ?>

</body>

</html>
