<?php echo $this->doctype() ?>
<!--[if IE 8]>
<html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <!--    --><?php //echo $this->headTitle('General Cavi Applicazione')->setSeparator(' - ')->setAutoEscape(false); ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico']); ?>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->

    <?php //$this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all');?>
    <?php $this->headLink()->appendStylesheet($this->url('assets') . 'assets/global/plugins/font-awesome/css/font-awesome.min.css')
        ->appendStylesheet($this->url('assets') . 'assets/global/plugins/simple-line-icons/simple-line-icons.min.css')
        ->appendStylesheet($this->url('assets') . 'assets/global/plugins/bootstrap/css/bootstrap.min.css')
        ->appendStylesheet($this->url('assets') . 'assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css'); ?>
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <?php $this->headLink()->appendStylesheet($this->url('assets') . 'assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.css')
        ->appendStylesheet($this->url('assets') . 'assets/global/plugins/morris/morris.css')
        ->appendStylesheet($this->url('assets') . 'assets/global/plugins/fullcalendar/fullcalendar.min.css')
        ->appendStylesheet($this->url('assets') . 'assets/global/plugins/jqvmap/jqvmap/jqvmap.css'); ?>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN THEME GLOBAL STYLES -->
    <?php $this->headLink()->appendStylesheet($this->url('assets') . 'assets/global/css/components.min.css', 'all', true, array('id' => 'style_components'))
        ->appendStylesheet($this->url('assets') . 'assets/global/css/plugins.min.css'); ?>
    <!-- END THEME GLOBAL STYLES -->
    <!-- BEGIN THEME LAYOUT STYLES -->
    <?php $this->headLink()->appendStylesheet($this->url('assets') . 'assets/layouts/layout/css/layout.min.css')
        ->appendStylesheet($this->url('assets') . 'assets/layouts/layout/css/themes/darkblue.min.css', 'all', true, array('id' => 'style_color'))
        ->appendStylesheet($this->url('assets') . 'assets/layouts/layout/css/custom.min.css'); ?>
    <?php $this->headLink()->appendStylesheet('/css/style.css', 'all', true, array('id' => 'localcss')); ?>
    <!-- END THEME LAYOUT STYLES -->
    <?php echo $this->headLink(); ?>

    <!-- Scripts -->
    <!-- BEGIN THEME LAYOUT SCRIPTS -->
    <?php $this->headScript()
        ->prependFile($this->url('assets') . 'assets/layouts/layout/scripts/layout.min.js', 'text/javascript')
    ?>
    <!-- BEGIN THEME GLOBAL SCRIPTS -->
    <?php $this->headScript()
        ->prependFile($this->url('assets') . 'assets/global/scripts/app.min.js', 'text/javascript');
    ?>
    <!-- END THEME GLOBAL SCRIPTS -->
    <!-- BEGIN GLOBAL PLUGINS -->
    <?php $this->headScript()
        ->prependFile($this->url('assets') . 'assets/global/scripts/app.min.js', 'text/javascript');
    ?>
    <!-- END GLOBAL PLUGINS -->
    <?php $this->headScript()
        ->prependFile($this->url('assets') . 'assets/global/plugins/ie8.fix.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
        ->prependFile($this->url('assets') . 'assets/global/plugins/excanvas.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
        ->prependFile($this->url('assets') . 'assets/global/plugins/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9'));
    ?>
    <!-- BEGIN CORE PLUGINS -->
    <?php $this->headScript()
        ->prependFile($this->url('assets') . 'assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js', 'text/javascript')
        ->prependFile($this->url('assets') . 'assets/global/plugins/jquery.blockui.min.js', 'text/javascript')
        ->prependFile($this->url('assets') . 'assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js', 'text/javascript')
        ->prependFile($this->url('assets') . 'assets/global/plugins/js.cookie.min.js', 'text/javascript')
        ->prependFile($this->url('assets') . 'assets/global/plugins/bootstrap/js/bootstrap.min.js', 'text/javascript')
        ->prependFile($this->url('assets') . 'assets/global/plugins/jquery.min.js', 'text/javascript');
    ?>
    <!-- END CORE PLUGINS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <!--    --><?php //echo $this->headScript()
    //        ->prependFile($this->basePath().'pages/scripts/dashboard.min.js'), 'text/javascript');
    //    ?>
    <!-- END PAGE LEVEL SCRIPTS -->
    <!-- END THEME LAYOUT SCRIPTS -->
    <?php echo $this->headScript(); ?>
    <?php echo $this->inlineScript(); ?>

</head>

<body class="page-header-fixed page-sidebar-closed-hide-logo page-content-white">
<div class="page-wrapper">
    <!-- BEGIN HEADER -->
    <div class="page-header navbar navbar-fixed-top">
        <!-- BEGIN HEADER INNER -->
        <div class="page-header-inner ">
            <!-- BEGIN LOGO -->
            <div class="page-logo">
            <?= $this->logo; ?>
                <div class="menu-toggler sidebar-toggler">
                    <span></span>
                </div>
            </div>
            <!-- END LOGO -->
            <!-- BEGIN RESPONSIVE MENU TOGGLER -->
            <a href="javascript:" class="menu-toggler responsive-toggler" data-toggle="collapse"
               data-target=".navbar-collapse">
                <span></span>
            </a>
            <!-- END RESPONSIVE MENU TOGGLER -->
            <!-- BEGIN TOP NAVIGATION MENU -->
            <?= $this->topMenu; ?>
            <!-- END TOP NAVIGATION MENU -->
        </div>
        <!-- END HEADER INNER -->
    </div>
    <!-- END HEADER -->
    <!-- BEGIN HEADER & CONTENT DIVIDER -->
    <div class="clearfix"></div>
    <!-- END HEADER & CONTENT DIVIDER -->
    <!-- BEGIN CONTAINER -->
    <div class="page-container">
        <!-- BEGIN SIDEBAR -->
        <?= $this->sideBar; ?>
        <!-- END SIDEBAR -->
        <!-- BEGIN CONTENT -->

        <div class="page-content-wrapper">


            <!-- BEGIN CONTENT BODY -->
            <div class="page-content" style="min-height: 20000px">
                <div class="page-bar">
                 <?php echo $this->navigation('Zend\Navigation\Breadcrumbs')->breadcrumbs()->setPartial('partials/breadcrumbs')->render(); ?>
                </div>
                <?php echo $this->content ?>
            </div>
            <!-- END CONTENT BODY -->
        </div>
        <!-- END CONTENT -->
        <!-- END CONTAINER -->
        <!-- BEGIN FOOTER -->
                <?php echo $this->footer ?>
        <!-- END FOOTER -->
</div>
    <?php echo $this->inlineScript() ?>

</body>


</html>
